### ISSUE TITLE
Stable bug with some version of beautifulsoup4 and html5lib

### ISSUE THREAD

**Issue by geosphere** [hypsurus/weeman#17]
```
./weeman.py 
Traceback (most recent call last):
  File "./weeman.py", line 63, in <module>
    main()
  File "./weeman.py", line 59, in main
    from core.shell import shell
  File "/opt/weeman/core/shell.py", line 27, in <module>
    from core.httpd import weeman
  File "/opt/weeman/core/httpd.py", line 19, in <module>
    from lib.bs4 import BeautifulSoup as bs
  File "/opt/weeman/lib/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/opt/weeman/lib/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/opt/weeman/lib/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
```

more about [bug](https://bugs.launchpad.net/beautifulsoup/+bug/1603299)

**Comment by geosphere** [comment]
#18 - fix commit

**Comment by hypsource** [comment]
Your pull request is invaild.
