### ISSUE TITLE
AttributeError: 'module' object has no attribute '_base'

### ISSUE THREAD

**Issue by eyadsibai** [hypsurus/weeman#20]
I am getting this error when running ```python2 weeman.py``` 

```Traceback (most recent call last):
  File "weeman.py", line 63, in <module>
    main()
  File "weeman.py", line 59, in main
    from core.shell import shell
  File "/usr/share/weeman/core/shell.py", line 27, in <module>
    from core.httpd import weeman
  File "/usr/share/weeman/core/httpd.py", line 19, in <module>
    from lib.bs4 import BeautifulSoup as bs
  File "/usr/share/weeman/lib/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/share/weeman/lib/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/share/weeman/lib/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
```

**Comment by hypsource** [comment]
Please specify Python version.
I will try to fix it.

**Comment by eyadsibai** [comment]
Thanks it is fixed now 👍

**Comment by eyadsibai** [comment]
the python version was 3.5
